using Godot;
namespace Game.Scripts.Tools;

[Tool]
[GlobalClass]
public partial class LevelCreator : Node3D
{
	private const string GeneratedMetaKey = "_scene_level_creator_generated";
	private const string GeneratedWorldMetaKey = "_scene_level_creator_world";
	private static readonly string[] RequiredChildren =
	{
		"Static",
		"Interactables",
		"Collectables",
		"Grabbables",
		"Rotatables"
	};
	[Export] private PackedScene worldScene;

	public override void _EnterTree()
	{
		if (Engine.IsEditorHint())
			CallDeferred(nameof(RebuildChildren));
	}

	private void RebuildChildren()
	{
		if (!Engine.IsEditorHint())
			return;

		if (worldScene != null && !HasGeneratedWorld())
		{
			Node world = worldScene.Instantiate();
			world.SetMeta(GeneratedWorldMetaKey, true);
			AddChild(world);
			world.Owner = Owner ?? this;
		}

		foreach (string childName in RequiredChildren)
		{
			Node existing = FindChild(childName, false, false);
			if (existing is Node3D existingNode3D)
			{
				if (!existingNode3D.HasMeta(GeneratedMetaKey))
					GD.PushWarning($"Level Creator: '{childName}' exists but was not generated by this script.");
				continue;
			}

			if (existing != null)
			{
				GD.PushWarning($"Level Creator: '{childName}' exists but is not Node3D.");
				continue;
			}

			Node3D child = new() { Name = childName };
			child.SetMeta(GeneratedMetaKey, true);
			AddChild(child);
			child.Owner = Owner ?? this;
		}
	}

	private bool HasGeneratedWorld()
	{
		foreach (Node child in GetChildren())
		{
			if (child.HasMeta(GeneratedWorldMetaKey))
				return true;
		}

		return false;
	}
}
